spring:
  security:
    oauth2:
      client:
        registration:
          appid-client:
            provider: appid-provider
            clientId: ${OAUTH_CLIENT_ID}
            clientSecret: ${OAUTH_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: openid,profile
        provider:
          appid-provider:
            issuerUri: ${OAUTH_ISSUER_URI}

logging:
  level:
    org:
      springframework:
        security: INFO
        boot: INFO
